version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/pnpm/store
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "pnpm install && pnpm dev"
    stdin_open: true
    tty: true

volumes:
  pnpm-store:
    driver: local